from __future__ import annotations

import json
from datetime import date
from hashlib import sha256
from pathlib import Path

from stock_analysis.ai_lab.selection import (
    LEGACY_STABILITY_PROMPT_VERSION,
    build_selection_plan,
)


def test_production_score_is_single_and_legacy_v3_matches_head_golden(
    cn_manifest: Path,
) -> None:
    production = build_selection_plan(
        market="CN",
        candidates_path=cn_manifest,
        as_of=date(2026, 7, 15),
        top_n=1,
    )
    legacy = build_selection_plan(
        market="CN",
        candidates_path=cn_manifest,
        as_of=date(2026, 7, 15),
        top_n=1,
        prompt_profile="legacy_stability_v3",
    )

    production_prompt = json.loads(production.prompt)
    assert "response_example" not in production_prompt
    assert all(
        "score" in candidate and "score" not in candidate["features"]
        for candidate in production_prompt["candidates"]
    )
    legacy_prompt = json.loads(legacy.prompt)
    assert legacy.prompt_version == LEGACY_STABILITY_PROMPT_VERSION
    assert legacy_prompt["response_example"]["picks"][0]["symbol"] == "600000.SH"
    assert all(
        candidate["features"]["score"] == candidate["score"]
        for candidate in legacy_prompt["candidates"]
    )
    # Golden hash generated by the frozen .3 renderer at repository HEAD.
    assert sha256(legacy.prompt.encode()).hexdigest() == (
        "f6e02974055f0ac00b8362c647cc2275f5a908a805c825bfa4615ee4003d6573"
    )
