from __future__ import annotations

import pytest

from ai_stock_picker.candidate_models import Candidate
from ai_stock_picker.commentary_validation import validate_customer_commentary


@pytest.fixture
def candidate() -> Candidate:
    return Candidate(
        symbol="AAPL",
        name="Apple Inc.",
        topic="Technology",
        score=9.0,
        features={
            "trend_score": 0.8,
            "intraday_stability_score": 0.7,
            "sector": "Technology",
        },
    )


def validate(value: str, candidate: Candidate, field: str = "reasoning") -> None:
    validate_customer_commentary(
        field,
        value,
        candidate,
        market="US",
        provider="deepseek",
        model="deepseek-chat",
    )


def test_accepts_grounded_commentary(candidate: Candidate) -> None:
    validate("The overall candidate score supports the relative ranking.", candidate)
    validate(
        "The candidate topic Technology is the supplied basis for this note.",
        candidate,
    )


def test_requires_actual_categorical_value(candidate: Candidate) -> None:
    with pytest.raises(ValueError, match="supplied candidate value"):
        validate("The candidate topic supports the ranking.", candidate)


def test_rejects_unsupported_field(candidate: Candidate) -> None:
    with pytest.raises(ValueError, match="unsupported candidate field"):
        validate("The earnings_growth_score supports the ranking.", candidate)


@pytest.mark.parametrize(
    ("value", "message"),
    [
        (
            "The overall candidate score supports a buy recommendation.",
            "trading advice",
        ),
        (
            "According to analysts, the overall candidate score supports the ranking.",
            "external or future claim",
        ),
        (
            "The overall candidate score supports the ranking at https://example.com.",
            "URL, address, or secret",
        ),
        (
            "The overall candidate score supports the ranking by DeepSeek.",
            "system metadata",
        ),
        (
            "The overall candidate score does not support the ranking.",
            "negates",
        ),
    ],
)
def test_rejects_forbidden_customer_content(
    candidate: Candidate, value: str, message: str
) -> None:
    with pytest.raises(ValueError, match=message):
        validate(value, candidate)


@pytest.mark.parametrize(
    "commentary",
    [
        "Higher intraday stability means higher risk for this candidate.",
        "Lower intraday stability means lower risk for this candidate.",
    ],
)
def test_stability_semantics_cannot_be_reversed(
    candidate: Candidate, commentary: str
) -> None:
    with pytest.raises(ValueError, match="stability semantics"):
        validate(commentary, candidate)


def test_chinese_locale_can_be_used_for_any_market(candidate: Candidate) -> None:
    validate_customer_commentary(
        "reasoning",
        "综合候选评分支持该股票的相对排序。",
        candidate,
        market="CN",
        provider="gemini",
        model="gemini-2.5-flash",
    )


def test_ordinary_accented_word_is_not_provider_metadata(candidate: Candidate) -> None:
    validate(
        "The overall candidate score supports a naïve relative comparison.",
        candidate,
    )


@pytest.mark.parametrize(
    "commentary",
    [
        "The overall candidate score was interpreted by DеepSeek.",
        "The overall candidate score was interpreted by α model.",
        "The overall candidate score is detailed at 10.0.0.8.",
        "The overall candidate score is detailed at 2001:db8::8.",
        "The overall candidate score is detailed at 例子.测试.",
        "The overall candidate score is detailed at analyst@example.com.",
        "Intraday stability is high, which means high risk.",
        "Intraday stability is high, which means more volatile behavior.",
        "Intraday stability is low, which means low risk.",
        "Intraday stability is low, so risk is low.",
        "The overall candidate score does not support the rank; intuition does.",
        "The overall candidate score reflects customer demand and competition.",
        "Based on the overall candidate score, investors should go long.",
        "The overall candidate score was generated by a language model.",
        "The overall candidate score was generated by a model.",
        "The overall candidate score was generated by an LLM.",
        "The overall candidate score includes provider name metadata.",
        "The overall candidate score is detailed at example.tech/path.",
        "综合候选评分 supports the relative ranking.",
        (
            "The ranking is not based on the overall candidate score; personal "
            "judgment is."
        ),
        "The overall candidate score suggests increasing exposure.",
        "Intraday stability is high, but the behavior is unstable.",
        "Intraday stability is low, yet it is more stable.",
    ],
)
def test_reviewer_policy_regressions_are_rejected(
    candidate: Candidate, commentary: str
) -> None:
    with pytest.raises(ValueError, match="provider output reasoning"):
        validate(commentary, candidate)


def test_grounding_alias_must_exist_on_candidate(candidate: Candidate) -> None:
    with pytest.raises(ValueError, match="field absent from its candidate"):
        validate("The liquidity signal supports this candidate.", candidate)


def test_decimal_percentage_is_not_treated_as_a_host(candidate: Candidate) -> None:
    candidate_with_return = Candidate(
        symbol=candidate.symbol,
        name=candidate.name,
        topic=candidate.topic,
        score=candidate.score,
        features={**candidate.features, "ret_5d": 0.0325},
    )
    validate(
        "The 5-day performance is 3.25% and supports the relative ranking.",
        candidate_with_return,
    )


def test_categorical_grounding_rejects_invented_coordinated_value(
    candidate: Candidate,
) -> None:
    candidate_with_topics = Candidate(
        symbol=candidate.symbol,
        name=candidate.name,
        topic=candidate.topic,
        score=candidate.score,
        features={**candidate.features, "source_topics": ["Technology"]},
    )
    with pytest.raises(ValueError, match="unsupported source_topics value"):
        validate(
            "The source topics Technology and AI model application support the rank.",
            candidate_with_topics,
        )


def test_categorical_grounding_allows_supplied_coordinated_values(
    candidate: Candidate,
) -> None:
    candidate_with_topics = Candidate(
        symbol=candidate.symbol,
        name=candidate.name,
        topic=candidate.topic,
        score=candidate.score,
        features={
            **candidate.features,
            "source_topics": ["Technology", "AI model application"],
        },
    )
    validate(
        "The source topics Technology and AI model application support the rank.",
        candidate_with_topics,
    )


@pytest.mark.parametrize(
    ("commentary", "message"),
    [
        ("综合候选评分支持排序，公司产品供不应求。", "external or future claim"),
        ("综合候选评分支持排序，建议逢低布局。", "trading advice"),
        ("较高的日内波动稳定性意味着风险更高。", "stability semantics"),
        ("综合候选评分支持排序。公司前景良好。", "without a supplied"),
    ],
)
def test_chinese_commentary_policy_regressions_are_rejected(
    candidate: Candidate,
    commentary: str,
    message: str,
) -> None:
    with pytest.raises(ValueError, match=message):
        validate_customer_commentary(
            "reasoning",
            commentary,
            candidate,
            market="CN",
            provider="gemini",
            model="gemini-2.5-flash",
        )
